### ISSUE TITLE
how can we use that library

### ISSUE THREAD

**Issue by fixajteknik** [beegee-tokyo/RUI3-Arduino-Library#2]
my circuit diagram is an esp32 s3 connected Serial1 to rak3172 wisduo board of Serial1. I can send data over UART each others . But I couldn't get your library to work in this setup. what should be prepair first?

1. which code should be in rak3172
2. your this https://github.com/beegee-tokyo/RUI3-Arduino-Library/blob/main/examples/RUI3-AT-OTAA/RUI3-AT-OTAA.ino I am testing, I thing it should be installed in esp32 s3
3. connection diagram?

my circuit
![image](https://github.com/user-attachments/assets/33427c6f-b4ed-406f-99aa-5f243d134264)

online this line changed`
volatile bool breakout_flag = true;`
OUTPUT:

```
10:41:23.116 -> Starting loop-through - exit with 'ESC' key
10:41:23.116 -> ===========================================
10:41:23.116 -> 
10:41:23.116 -> Clear Serial1 RX buffer.
10:41:28.130 -> ===========================================
10:41:28.130 -> Convert byte array to ASCII array
10:41:28.130 -> Result: 000102030405060708090A0B0C0D0E0F
10:41:28.130 -> ===========================================
10:41:28.130 -> Convert ASCII array to byte array
10:41:28.130 -> Result: {00,01,02,03,04,05,06,07,08,09,0A,0B,0C,0D,0E,0F,}
10:41:28.130 -> ===========================================
10:41:28.130 -> Get version
10:41:34.149 -> Response: NO_RESPONSE
10:41:56.251 -> Try to set work mode.
10:42:07.322 -> set work_mode failed, please reset module.
```

**Comment by beegee-tokyo** [comment]
On the RAK31723 Evaluation Board, AT commands work only over the USB (== UART2).
If you need UART1 (_**ATTENTION**_ UART1 does not work in low power mode) you have to explicit enable it with `Serial1.begin(115200, RAK_AT_MODE);`

**Comment by fixajteknik** [comment]
can you show me a simple example such as at+ver=?. how can I get version of rak module with in code. thanks

**Comment by fixajteknik** [comment]
yes I understand thanks. esp32 should send the at commands over the serial1
